version: '2'
services:
  tensorflow:
    build:
      context: .
      dockerfile: Dockerfile
    # working_dir: /home/docker
    volumes:
      - ./notebooks:/notebooks
      - /usr/lib/x86_64-linux-gnu/libcuda.so:/usr/lib/x86_64-linux-gnu/libcuda.so
      - /usr/lib/x86_64-linux-gnu/libcuda.so.1:/usr/lib/x86_64-linux-gnu/libcuda.so.1
      - /usr/lib/x86_64-linux-gnu/libcuda.so.346.46:/usr/lib/x86_64-linux-gnu/libcuda.so.346.46
    ports:
      - "8888:8888"
      - "6006:6006"
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-uvm:/dev/nvidia-uvm
